apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jupyterhub
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift
    repoURL: https://github.com/glennf/z2jh-openshift.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
